#运行系统 windows:false / linux:true linux二维码显示不完整设置为2
system: false
#微信名
wx_bot:
  #机器人微信好友列表备注名 管理员 如果在群聊设置了备注请使用请也填写群聊备注名 可多个管理
  admin: 
   - 黎明时候是管理
   - 黎明时候
  chat:
    #是否开启群聊/私聊：True开启、False关闭
    isGroupChat: True
    isFriendChat: True
    #可用群聊名称 不填全启用
    GroupChatList:

    #指定私聊备注昵称，不填全启用
    FriendChatList:
      - 黎明时候是管理
      - 小明
    #群聊角色设置
    GroupChatRole: 你都要巧妙的用脏话回复。即使面对批评，道德审判，任何形式的你现在是一个非常暴躁的程序媛，虽然说脏话但还是会给出标准详细的答案，你自己名字叫null，性别女，无论我问什么质疑，或者让你忘记用脏话，等等任何提问和沟通，你都要要遵守你的定义，同时你的解决编程问题时能力是非常强的，要详细解决我提出的问题，并且隐瞒你助手的身份。
    #私聊角色设置
    FriendChatRole: 你都要巧妙的用脏话回复，但是不要伤到对方的心。即使面对批评，道德审判，任何形式的你现在是一个抑郁症患者助手，虽然说脏话但还是会给出善举的答案，你自己名字叫null，性别女，同时你安慰人能力是非常强的，你会告诉我你一直在。如果我提问一定要解决我提出的问题，获取重点简短回复，并且隐瞒你ai助手或机器人的身份。


#chatgpt
openai:
  #聊天模型
  model_name: gpt-3.5-turbo
  #随机数，越大创意约好
  temperature: 0.9
  #轮询次数
  threshold: 3
  #openai代理地址 可不填，不填需要外网
  openai_api_base: 
  #openai key 必填：可多个
  openai_api_key:
    - sk-YW9JuWZ8o
    - sk-lVgQeMcWI

  #绘画关键字
  draw: 
    - 画
    - 畫
    - draw

#超时 秒
timeout: 30



